### ISSUE TITLE
Add Resources page

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#20]
Resources include documentation, tutorials, source code. See: https://github.com/Pylons/trypyramid/blob/master/index.html#L67-L93

When page is added, add a link in the navbar, too.

**Comment by cguardia** [comment]
The problem I see with the navbar, is that it only shows up when the user scrolls down. Shouldn't the links to resources and (specially) documentation be up there and visible right away?

**Comment by blaflamme** [comment]
@cguardia the idea is that the top is like an intro slide, then when you start scrolling to see content the main menu appears and gives you more choices.

**Comment by stevepiercy** [comment]
The reason that the navigation is hidden *now* is because there is only one page *now*. As soon as a second page is added through a PR, then it makes sense to show the navigation at all times. @blaflamme @cguardia do you agree?

**Comment by blaflamme** [comment]
i would let the top menu behave like this on the home page and be at the top on all other pages

**Comment by stevepiercy** [comment]
I appreciate aesthetics, but not at the expense of usability. Maybe it's just me, but as soon as I start scrolling down a page, I focus on where I am scrolling *toward* and *down* and not to what I scrolled away *from* or *above*.

If the decision comes down to not showing navigation everywhere, then there must be something prominent on the home page to lead the user to Documentation and Tutorials. That would mean a rewrite and reorganization of the home page content.

I think visible navigation everywhere is the lesser of the two evils.

**Comment by mmerickel** [comment]
I've become pretty used to sites that use the persistent nav bar that sticks to the top when you scroll.

**Comment by ergo** [comment]
@mmerickel this is what https://github.com/Pylons/tpc/pull/26 does exactly.

**Comment by blaflamme** [comment]
@stevepiercy the topbar on the home page appears as soon as you pass the hero section, then it sticks there. When you'll go to any other page you'll have the topnav there since only the home page will have the hero section. So it's a unique behaviour on the home page to emphasis on the brand or any other relevant information, like a business card or a flyer, then you'll see the topnav after, like you see your name, address and email on your business card, the emphasis is not on your name or your email but on the general mood you want to communicate.

Any new comers will start scrolling to reach more content and will see the topnav appearing at the top so he'll have the choice to continue scrolling or go to any other page from the menu, but he's in discover mode and looking at everything to spot information he can understand quickly. Users like us will directly go to the docs site or any other page but the fact that the topnav is hidden at first on the initial page load will never prevent a user from reaching content. To happen a user will have to be totally passive, doing nothing and not trying to see what's there, so in that case I can't think he could have found a way to reach our site anyways.

**Comment by blaflamme** [comment]
@mmerickel the current implementation does that when it shows up

**Comment by stevepiercy** [comment]
@blaflamme I don't know about other users, but for me alone, I don't look back *up* once I start scrolling *down*.

Additionally, I don't expect to need to scroll down to reveal a hidden navigation object, so my brain does not register its appearance.

Maybe it's me aging and losing my visual acuity? I'm sensitive to accessibility, too.

I think you can achieve what you want with a universally sticky or fixed nav with a hero section. It might mean losing the some branding that you want, but I think the trade-off is worth it.

Sticky nav example:
https://selectree.calpoly.edu/search-trees-by-characteristics

Fixed nav examples:
http://getbootstrap.com/
https://www.djangoproject.com/

**Comment by stevepiercy** [comment]
Closing because this will be resolved by merging #30.
