### ISSUE TITLE
Improve styling under "Try Pyramid" heading

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/tpc#6]
Some suggestions:

1) Center the "Try Pyramid" heading. It's a two column layout in that spot. The other headings have a variety of left/right justification. I think it might look better having the heading aligned over both columns.

2) Reduce repetition of "Pyramid". "Pyramid Hello World Application" -> "Hello World". "Pyramid is easy to setup and use" -> "Easy to Start".

3) Right column subheadings -> Numbered list. For example..

1. *Install Python* from _python.org_.
2. Install Pyramid: (followed by bash snippet)
3. Create your first app:
4. Run it:
5. Open it:

4) Reduce code snippet margin-top and margin-bottom.

If you agree with this, I'll make the changes.

**Comment by pauleveritt** [comment]
As another suggestion, let's leave out the installation of waitress from the "Hello World" example on the home page.

**Comment by pauleveritt** [comment]
Oops, sorry, another example. IMO, the "create_app" function is superfluous. We can just put everything under the if __name__ part. If, though, that's now the preferred style, I can update the Quick Tour and Quick Tutorial to use that style.

**Comment by blaflamme** [comment]
@pauleveritt yes I agree, most of the suggestions seems right. Point #4 is not as easy as it seems. I'll be pushing a top bar soon.

**Comment by stevepiercy** [comment]
1. I disagree. I don't want my eye to track right-to-left from heading to a new line of content.
2. Agree.
3. I prefer the specificity and repetition of "app" over the ambiguous pronoun "it", e.g., "Am I running a command or an app?"
4. I think it's not a margin, but an element height. I cannot tell where the height comes from. As a workaround, we could set ``pre.nobs {margin: 0 0 -1.5em 0;}``
5. Agree, remove ``waitress``.
6. Agree on ``name``.
7. @blaflamme the first mention of "Pyramid" on the home page is "Try Pyramid". I think we need to have the name somewhere "above the fold".
8. @blaflamme in choosing colors, please select contrasting colors for people with vision impairments, including color blindness.

**Comment by blaflamme** [comment]
#4 I know I can do that and I'll do it, but that's an ugly hack :(

**Comment by blaflamme** [comment]
I'm also working on improving content sections/blocks this afternoon, they're not done

**Comment by blaflamme** [comment]
@stevepiercy #7 pull latest, we have the top bar back now

**Comment by stevepiercy** [comment]
#4 Yeah, it sucks, but I could find no CSS declaration that calculated the height of the <pre> element. Where the heck does it come from?

**Comment by blaflamme** [comment]
@stevepiercy yeah that's weird. If I omit the github css everything is ok, but no styling, and in the github css file there's nothing there to add that padding/margin. I hate putting negative values because I don't know the issue but that's it for now :(

**Comment by stevepiercy** [comment]
Did you mean Twitter Bootstrap CSS instead of GitHub CSS?

@blaflamme pulled down latest commits. Here are a few more suggestions.
1. Spacing between ``<h1>`` in header and top nav bar is too much.
2. Logo and project name is too small relative to header text. I've seen some sites that handle this with a "shrink on scroll down" top navbar. SO post with link to demo: http://stackoverflow.com/a/27050993/2214933
3. Red color on "Try Pyramid" is a great improvement.
4. Code light grey background color is indistinguishable from light beige background of the content row. Please increase contrast.
5. I prefer a single column and a single linear flow of content, especially when the screen is < 992px wide. I lose my place jumping/scrolling back and forth, even if it is a few steps. Perhaps a ``.col-md-6 .col-md-offset-3`` or  ``.col-md-8 .col-md-offset-2`` would work?
6. HTML5 and CSS3 icons should be removed form the footer. I'm not sure about the GitHub icon. If it stays, then it needs a link and a contrasting, lighter color.
7. Add copyright and license to footer. @pauleveritt should copyright be Agendaless Consulting? See http://docs.pylonsproject.org/projects/pyramid/en/latest/copyright.html

**Comment by blaflamme** [comment]
@stevepiercy Yeah it looks like the header adds somehow more spacing than the default assigned, probably a tag padding/margin that needs to be fixed. For the moment the navbar is at the top, what I think is to move it after the hero block and stick at top after, or add it when the hero block disapear, I'm not set.

**Comment by stevepiercy** [comment]
@blaflamme I really like what you've done. This is beautiful, fantastic work! I'm closing this issue because they are all resolved or have separate Issues or PRs.

**Comment by blaflamme** [comment]
@stevepiercy thanks
